"use client";
import {FormEvent,useState} from "react";import {useRouter} from "next/navigation";
type Category={id:string;name:string;slug:string};type Initial={id:string;title:string;slug:string;excerpt:string;content:string;image_url:string|null;status:"draft"|"published"|"archived";reading_minutes:number|null;categoryId:string;tags:string};
export default function ArticleForm({categories,initial}:{categories:Category[];initial?:Initial}){
 const router=useRouter();const[busy,setBusy]=useState(false);const[aiBusy,setAiBusy]=useState(false);const[error,setError]=useState("");const[aiMessage,setAiMessage]=useState("");const[f,setF]=useState({title:initial?.title??"",slug:initial?.slug??"",excerpt:initial?.excerpt??"",content:initial?.content??"",status:initial?.status??"draft",categoryId:initial?.categoryId??categories[0]?.id??"",tags:initial?.tags??"",readingMinutes:initial?.reading_minutes?.toString()??"",imageUrl:initial?.image_url??""});
 const set=(k:keyof typeof f,v:string)=>setF(x=>({...x,[k]:v}));
 async function suggestWithAI(){if(!initial)return;setAiBusy(true);setError("");setAiMessage("");const r=await fetch("/api/admin/ai/enrich",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({articleId:initial.id})});const j=await r.json().catch(()=>({}));if(!r.ok){setError(j.error||"AI ช่วยร่างไม่สำเร็จ");setAiBusy(false);return}const s=j.suggestion;const category=categories.find(c=>c.slug===s.categorySlug);setF(x=>({...x,title:s.title||x.title,excerpt:s.excerpt||x.excerpt,categoryId:category?.id??x.categoryId,tags:Array.isArray(s.tags)?s.tags.join(", "):x.tags,readingMinutes:String(s.readingMinutes||x.readingMinutes||1)}));setAiMessage("AI เสนอร่างแล้ว — ตรวจแก้ก่อนบันทึก/เผยแพร่");setAiBusy(false)}
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");const r=await fetch(initial?"/api/admin/articles/"+initial.id:"/api/admin/articles",{method:initial?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(f)});const j=await r.json().catch(()=>({}));if(!r.ok){setError(j.error||"บันทึกไม่สำเร็จ");setBusy(false);return}router.push("/admin");router.refresh()}
 const qualityMissing=[!f.title.trim()?"หัวข้อ":"",!f.excerpt.trim()?"คำโปรย":"",!f.content.trim()?"เนื้อหา":"",!f.categoryId?"หมวดหมู่":"",!f.tags.trim()?"แท็ก":""].filter(Boolean);
 return <form className="admin-form" onSubmit={submit}>{error&&<div className="ui-state is-error"><div><strong>เกิดข้อผิดพลาด</strong><p>{error}</p></div></div>}{aiMessage&&<div className="ui-state"><div><strong>AI Editorial</strong><p>{aiMessage}</p></div></div>}
 <div className="ui-state"><div><strong>{qualityMissing.length ? `ยังขาด ${qualityMissing.length} จุดก่อนเผยแพร่` : "ข้อมูลหลักพร้อมสำหรับการตรวจเผยแพร่"}</strong><p>{qualityMissing.length ? `ขาด: ${qualityMissing.join(" · ")}` : "ระบบจะตรวจซ้ำที่ API ก่อนเผยแพร่"}</p></div></div>
 <div className="admin-form-tools">{initial&&<button type="button" className="state-action" onClick={suggestWithAI} disabled={aiBusy||busy}>{aiBusy?"กำลังให้ AI ช่วยร่าง…":"✨ AI ช่วยร่าง"}</button>}<span>AI เป็นผู้ช่วยเสนอหัวข้อ คำโปรย หมวดหมู่ แท็ก และเวลาอ่านเท่านั้น บรรณาธิการเป็นผู้ตรวจและตัดสินใจก่อนเผยแพร่</span></div>
 <label>หัวข้อ<input required value={f.title} onChange={e=>set("title",e.target.value)}/></label>
 <label>Slug<input required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value={f.slug} onChange={e=>set("slug",e.target.value)}/><span>ภาษาอังกฤษตัวเล็ก ตัวเลข และ -</span></label>
 <label>หมวดหมู่<select required value={f.categoryId} onChange={e=>set("categoryId",e.target.value)}>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
 <label>สถานะ<select value={f.status} onChange={e=>set("status",e.target.value)}><option value="draft">ฉบับร่าง</option><option value="published">เผยแพร่</option><option value="archived">เก็บถาวร</option></select></label>
 <label>รูปภาพข่าว (URL)<input type="url" value={f.imageUrl} onChange={e=>set("imageUrl",e.target.value)} placeholder="https://…"/><span>ใส่ URL รูปภาพต้นทางแบบ HTTPS ได้ ไม่บังคับ</span></label>
 <label>คำโปรย<textarea rows={3} value={f.excerpt} onChange={e=>set("excerpt",e.target.value)}/></label>
 <label>เนื้อหา<textarea required rows={14} value={f.content} onChange={e=>set("content",e.target.value)}/></label>
 <label>Tags<input value={f.tags} onChange={e=>set("tags",e.target.value)}/><span>คั่นด้วย comma เช่น technology, innovation</span></label>
 <label>เวลาอ่าน (นาที)<input type="number" min="1" value={f.readingMinutes} onChange={e=>set("readingMinutes",e.target.value)}/></label>
 <div className="admin-form-actions"><button className="primary-button" disabled={busy}>{busy?"กำลังบันทึก…":initial?"บันทึกการแก้ไข":"สร้างข่าว"}</button><button type="button" className="state-action" onClick={()=>router.push("/admin")}>ยกเลิก</button></div>
 </form>;
}